//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public string userName { get; set; }
        public string password { get; set; }
        public string fullNmae { get; set; }
        public string email { get; set; }
        public string website { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
